-- =============================================================
-- PARTE 1 - Bootstrap para uma conta Snowflake administrada
-- Execute no Snowsight com a role ACCOUNTADMIN.
--
-- Antes de executar:
-- 1. Gere o par de chaves com:
--    powershell -ExecutionPolicy Bypass -File
--      airflow-seminario/scripts/generate_snowflake_key_pair.ps1
-- 2. Substitua COLE_AQUI_A_CHAVE_PUBLICA pelo texto exibido,
--    sem BEGIN PUBLIC KEY, END PUBLIC KEY ou quebras de linha.
-- =============================================================

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS PFI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse do pipeline acadêmico Airflow, dbt e ML';

CREATE DATABASE IF NOT EXISTS PROJETO_FINAL_IA
    COMMENT = 'Projeto integrado de dados da PRF e machine learning';

CREATE SCHEMA IF NOT EXISTS PROJETO_FINAL_IA.RAW
    COMMENT = 'Dados brutos carregados do S3';

CREATE SCHEMA IF NOT EXISTS PROJETO_FINAL_IA.STAGING
    COMMENT = 'Padronização inicial realizada pelo dbt';

CREATE SCHEMA IF NOT EXISTS PROJETO_FINAL_IA.INTERMEDIATE
    COMMENT = 'Transformações intermediárias e enriquecimentos';

CREATE SCHEMA IF NOT EXISTS PROJETO_FINAL_IA.MART
    COMMENT = 'Tabelas analíticas consumidas pelo Metabase';

CREATE SCHEMA IF NOT EXISTS PROJETO_FINAL_IA.ML
    COMMENT = 'Features, predições e métricas de machine learning';

CREATE ROLE IF NOT EXISTS PFI_PIPELINE_ROLE
    COMMENT = 'Role técnica usada pelo Airflow e pelo dbt';

GRANT USAGE ON WAREHOUSE PFI_WH TO ROLE PFI_PIPELINE_ROLE;
GRANT USAGE ON DATABASE PROJETO_FINAL_IA TO ROLE PFI_PIPELINE_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA PROJETO_FINAL_IA.RAW
    TO ROLE PFI_PIPELINE_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA PROJETO_FINAL_IA.STAGING
    TO ROLE PFI_PIPELINE_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA PROJETO_FINAL_IA.INTERMEDIATE
    TO ROLE PFI_PIPELINE_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA PROJETO_FINAL_IA.MART
    TO ROLE PFI_PIPELINE_ROLE;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA PROJETO_FINAL_IA.ML
    TO ROLE PFI_PIPELINE_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN DATABASE PROJETO_FINAL_IA
    TO ROLE PFI_PIPELINE_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN DATABASE PROJETO_FINAL_IA
    TO ROLE PFI_PIPELINE_ROLE;

GRANT SELECT
    ON ALL VIEWS IN DATABASE PROJETO_FINAL_IA
    TO ROLE PFI_PIPELINE_ROLE;

GRANT SELECT
    ON FUTURE VIEWS IN DATABASE PROJETO_FINAL_IA
    TO ROLE PFI_PIPELINE_ROLE;

CREATE USER IF NOT EXISTS PFI_AIRFLOW
    TYPE = SERVICE
    DEFAULT_ROLE = PFI_PIPELINE_ROLE
    DEFAULT_WAREHOUSE = PFI_WH
    DEFAULT_NAMESPACE = PROJETO_FINAL_IA.STAGING
    DEFAULT_SECONDARY_ROLES = ()
    COMMENT = 'Usuário técnico do Airflow e dbt';

ALTER USER PFI_AIRFLOW
    SET RSA_PUBLIC_KEY = 'COLE_AQUI_A_CHAVE_PUBLICA';

GRANT ROLE PFI_PIPELINE_ROLE TO USER PFI_AIRFLOW;

-- Informações necessárias para preencher o arquivo .env.
SELECT
    CURRENT_ORGANIZATION_NAME() AS ORGANIZATION_NAME,
    CURRENT_ACCOUNT_NAME() AS ACCOUNT_NAME,
    CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME()
        AS SNOWFLAKE_ACCOUNT_PARA_ENV;

-- Validações visuais.
SHOW WAREHOUSES LIKE 'PFI_WH';
SHOW DATABASES LIKE 'PROJETO_FINAL_IA';
SHOW USERS LIKE 'PFI_AIRFLOW';
SHOW GRANTS TO ROLE PFI_PIPELINE_ROLE;
