projeto_final:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'PFI_AIRFLOW') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH', '/opt/airflow/keys/snowflake_rsa_key.p8') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'PFI_PIPELINE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'PFI_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'PROJETO_FINAL_IA') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'STAGING') }}"
      threads: 4
      client_session_keep_alive: false
